language: java
jdk:
  - openjdk8
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - sudo chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - sudo mkdir -p ~/app/step2/before-deploy
  - sudo chmod +x ~/app/step2/before-deploy
  - sudo cp scripts/*.sh ~/app/step2/before-deploy/
  - sudo cp appspec.yml ~/app/step2/before-deploy/
  - sudo cp build/libs/*.jar ~/app/step2/before-deploy/
  - sudo zip -r ~/app/step2/before-deploy *
  - sudo mv ~/app/step2/before-deploy/before-deploy.zip ~/app/step2/zip/js2n94-springboot2-project.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: js2n94-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: js2n94-springboot-build
    key: js2n94-springboot2-project.zip
    bundle_type: zip
    application: js2n94-springboot2-webservice
    deployment_group: js2n94-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람.
notifications:
  eamil:
    recipients:
      - yoosijisun12@gmail.com